menu__start    = "New game"
menu__load     = "Load game"
menu__settings = "Settings"
menu__quit     = "Quit game"

menu__lang     = "English" # write your language's name in your lang
menu__langcur  = "Currently used language:"
menu__langav   = "Available languages:"

# tutorial tips
game__tut_1 = "Welcome in Between Shadows and Light! This tutorial will guide you through game's interface."
game__tut_2 = "Pierwszym elementem gry jest stworzenie postaci, stąd za chwilę do tego przejdziemy - jest to dość istotna kwestia, jednak nie musisz się stresować, gdy nie wiesz, co dokładnie zrobić: gra stara się być tak dostosowana, by gracz z dowolnymi statystykami mógł ją względnie miło ukończyć"
game__tut_3 = "Istotne wspomnieć jest, że każda statystyka, umiejętność, cecha czy klasa, którą wybierzesz, będzie miała niemały wpływ na dalszy przebieg rozgrywki - wiele tych różnic jednak będziesz mógł zatrzeć w miarę gry, gdyż pierwsze wybory są na równi znaczące, jak i dalej: styl gry i wybory w niej dokonywane"

# creation of character
game__crq_1 = "How should your hero be named?"
game__crq_2 = "What sex should it be?"
game__crq_3 = "What race do you represent?"
game__crq_4 = "What class do you choose?"

# level up
game__up_atr = "Pick ability you want to improve"
game__up_skl = "Pick skill you want to improve"

# gender
gender__1 = "Male"
gender__2 = "Female"
gender__3 = "Nonbinary"

# races
race__human         = "Human"
race__human_descr   = "..."
race__vindean       = "Vindean"
race__vindean_descr = "..."
race__ett           = "Ett"
race__ett_descr     = "..."
race__saphtri       = "Saphtri"
race__saphtri_descr = "..."
race__voitri        = "Voitri"
race__voitri_descr  = "..."
race__ormath        = "Ormath"
race__ormath_descr  = "..."

# classes
class__undefined  = "Undefined"
class__warrior    = "Warrior"
class__gunslinger = "Gunslinger"
class__mage       = "Mage"
class__merchant   = "Merchant"
class__assassin   = "Assassin"
class__engineer   = "Engineer"
class__outlander  = "Outlander"
class__necromant  = "Necromant"
class__healer     = "Healer"
class__shaman     = "Ormath Shaman"

# locations
location__ship        = "'Arennan' Ship"
location__ship_docked = "'Arennan' Ship"
location__docks       = "Evros Docks"
location__evros       = "Evros City"
location__fields      = "Evros Fields"

# game
button__character = "Character"
button__inventory = "Inventory"
button__location  = "Location"
button__map       = "Map"
button__diary     = "Diary"